version: "3"

services:
  db:
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB=djang_djang
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    restart: always
    expose:
      - "5432"
  backend:
    build: ./backend
    depends_on:
      - db
    expose:
      - "8000"
    restart: always
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always